---
- hosts: webservers
  become: yes
  tasks: 
   - name: install java 8 on ubuntu
     apt:
      name: openjdk-8-jdk
      state: present
     when: ansible_os_family=="Debian"

   -  name: install java 8 on ubuntu
      yum: 
       name: java-1.8.0-openjdk-devel
       state: present
      when: ansible_os_family=="Redhat"

