---
- hosts: 172.31.28.160
  become: yes
  tasks: 
  - name: git install
    apt: 
     name:  git
     state: present

  -  name: install tree
     apt: 
       name: tree
       state: present

  -  name: install wget
     apt:
       name: wget
       state: present 