---
- name: deploy java application on my prod server
  get_url:
      url: https://elasticbeanstalk-ap-south-1-150900814845.s3.ap-south-1.amazonaws.com/.elasticbeanstalk
      dest: /opt/tomcat/webapps/.elasticbeanstalk
      force_basic_auth: yes