---

- name: create directory
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: extract tar file
  command:
    cmd: tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE


